src/main/java/com/clouddesigner/entities/User.java
package com.clouddesigner.entities;

import java.io.Serializable;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * The persistent class for the users database table.
 * 
 */
@Entity
@Table(name = "users")
@NamedQueries({
		@NamedQuery(name = "User.getByLogin", query = "select u from User u where u.login=:login"),
		@NamedQuery(name = "User.getAll", query = "SELECT u FROM User u"),
		@NamedQuery(name = "User.getById", query = "select u from User u where u.id=:id") })
public class User implements Serializable {

	private static final long serialVersionUID = 1L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	private String login;

	private String name;

	private String password;

	private String theme;

	@OneToMany(mappedBy = "user", fetch = FetchType.LAZY)
	private Set<AllowedUser> sharedProjects;

	@OneToMany(mappedBy = "owner", fetch = FetchType.LAZY, cascade = CascadeType.ALL)
	private Set<Project> ownedProjects;

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "user_roles", joinColumns = { @JoinColumn(name = "id_user") }, inverseJoinColumns = { @JoinColumn(name = "id_roles") })
	private Set<Role> roles;

	public User() {
	}

	public User(String login, String name) {
		this.login = login;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	public Set<AllowedUser> getSharedProjects() {
		return sharedProjects;
	}

	public void setSharedProjects(Set<AllowedUser> sharedProjects) {
		this.sharedProjects = sharedProjects;
	}

	public Set<Project> getOwnedProjects() {
		return ownedProjects;
	}

	public void setOwnedProjects(Set<Project> ownedProjects) {
		this.ownedProjects = ownedProjects;
	}

	@Override
	public int hashCode() {
		if (id == null)
			return super.hashCode();
		else
			return id;
	}

	@Override
	public boolean equals(Object obj) {
		if (id == null || obj == null || !(obj instanceof User))
			return super.equals(obj);
		else
			return id.equals(((User) obj).getId());
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder(this.getClass()
				.getSimpleName()).append(" ");
		builder.append("[");
		builder.append("id: ").append(id).append(", ");
		builder.append("login: ").append(login).append(", ");
		builder.append("name: ").append(name).append(", ");
		builder.append("password_size: ").append(password.length());
		builder.append("]");

		return builder.toString();
	}

	public String getTheme() {
		return theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}
}

src/main/java/com/clouddesigner/controller/CurrentUserController.java
package com.clouddesigner.controller;

import java.io.Serializable;
import java.security.Principal;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.clouddesigner.entities.Role;
import com.clouddesigner.entities.User;
import com.clouddesigner.model.facade.UsersFacade;

@Named
@SessionScoped
public class CurrentUserController implements Serializable {

	private static final long serialVersionUID = 1L;

	private User usuario;

	@Inject
	private Principal userPrincipal;

	@Inject
	private UsersFacade usersFacade;

	@PostConstruct
	public void load() throws Exception {
		usuario = usersFacade.getByLogin(userPrincipal.getName());
	}

	public void logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	}

	public User getUsuario() {
		return usuario;
	}

	public boolean isLogado() {
		return this.getUsuario() != null;
	}

	public boolean isInRole(String role) {
		return FacesContext.getCurrentInstance().getExternalContext().isUserInRole(role);
	}

	public boolean isAdmin() {
		return isInRole("ADMIN");
	}

	public String getTheme() {
		if (usuario.getTheme() == null || usuario.getTheme().isEmpty())
			usuario.setTheme("black-tie");
		return usuario.getTheme();
	}

	public void setTheme(String theme) {
		usuario.setTheme(theme);
	}

	public void publishChange() {	
		usuario = usersFacade.update(usuario);
	}
	
	public String rolesUser(){
		StringBuffer roles = new StringBuffer();
		for(Role r: usuario.getRoles()){
			roles.append(r.getRoleName());
			roles.append(", ");
			
		}
		if(roles.length()>2)
			roles.replace(roles.length()-2, roles.length()-1, "");
		return roles.toString();
	}
	
	public String getLogin(){
		return usuario.getLogin();
	}
	
}

src/main/java/com/clouddesigner/controller/DesignerController.java
package com.clouddesigner.controller;

import java.io.Serializable;

import javax.annotation.PreDestroy;
import javax.ejb.EJBException;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.transaction.HeuristicMixedException;
import javax.transaction.HeuristicRollbackException;
import javax.transaction.NotSupportedException;
import javax.transaction.RollbackException;
import javax.transaction.SystemException;

import com.clouddesigner.component.model.DbModel;
import com.clouddesigner.entities.Project;
import com.clouddesigner.entities.transients.Permission;
import com.clouddesigner.model.facade.DatabasesFacade;
import com.clouddesigner.model.facade.ProjectFacade;
import com.clouddesigner.model.facade.ProjectInstancesManagerFacade;
import com.clouddesigner.util.log.Log;

@Named
@ViewScoped
public class DesignerController implements Serializable {
	private static final long serialVersionUID = 1L;
	@Inject
	private Log log;
	@Inject
	private ProjectFacade projectsFacade;
	@Inject
	private CurrentUserController userController;
	@Inject
	private ProjectInstancesManagerFacade projectEditorFacade;
	@Inject
	private DatabasesFacade databasesFacade;

	private Integer id;
	private Integer idModel;

	private DbModel activeModel;

	private Permission permission;

	private Project project;

	public void loadModelFromId() {
		try {
			project = projectsFacade.getProjectByIdByUser(id,
					userController.getUsuario());
			if (project != null) {
				activeModel = project.getModel();
				idModel = activeModel.getId();
				this.permission = projectEditorFacade.openProject(
						projectsFacade.merge(project),
						userController.getUsuario());
			}
		} catch (EJBException e) {
			log.i("Projeto de id {0} não encontrado!", id);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	@PreDestroy
	public void closeProject() {
		System.out.println("DesignerController.closeProject()");
		projectEditorFacade.closeProject(project, userController.getUsuario());
	}

	public void saveModel() throws NotSupportedException, SystemException,
			SecurityException, IllegalStateException, RollbackException,
			HeuristicMixedException, HeuristicRollbackException {
		if (this.permission.canEdit()) {
			try {
				activeModel.setDatabase(databasesFacade
						.getDataBaseByName(activeModel.getDatabase().getDb()));
				project.setModel(activeModel);
				project = projectsFacade.insert(project);
				projectsFacade.removeModelById(idModel);
				idModel = project.getModel().getId();
				FacesContext.getCurrentInstance().addMessage(
						null,
						new FacesMessage(FacesMessage.SEVERITY_INFO, project
								.getName(), "Modelo salvo com sucesso!"));
			} catch (Exception e) {
				FacesContext.getCurrentInstance().addMessage(
						null,
						new FacesMessage(FacesMessage.SEVERITY_ERROR, "ERRO!",
								e.getMessage()));
			}
		} else {
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_WARN,
							"Permissão Negada!", "Usuário "
									+ userController.getLogin()
									+ " sem permissão."));
		}
	}

	public DbModel getActiveModel() {
		if (activeModel == null)
			loadModelFromId();
		return activeModel;
	}

	public void setActiveModel(DbModel activeModel) {
		this.activeModel = activeModel;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Project getProject() {
		return project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public Permission getPermission() {
		return permission;
	}

	public void setPermission(Permission permission) {
		this.permission = permission;
	}

}

src/main/java/com/clouddesigner/controller/ProjectListController.java
package com.clouddesigner.controller;

import java.io.BufferedReader;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.NoResultException;
import javax.xml.transform.TransformerException;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;

import com.clouddesigner.component.model.DbModel;
import com.clouddesigner.component.translator.ModelTranslator;
import com.clouddesigner.entities.Project;
import com.clouddesigner.exceptions.InvalidXmlEntryException;
import com.clouddesigner.model.facade.DatabasesFacade;
import com.clouddesigner.model.facade.ProjectFacade;
import com.clouddesigner.util.log.Log;
import com.clouddesigner.xml.XmlParser;

@Named
@ViewScoped
public class ProjectListController implements Serializable {

	private static final long serialVersionUID = 1L;
	@Inject
	private Log log;

	@Inject
	private ProjectFacade projectFacade;

	@Inject
	private DatabasesFacade databasesFacade;

	@Inject
	private CurrentUserController userController;

	@Inject
	private ProjectCrudController crud;

	private Project selectedProject;

	private List<Project> projects;

	@PostConstruct
	public void loadProjects() {
		log.t("ProjectListController.loadProjects()");
		projects = projectFacade.getAllProjectList(userController.getUsuario());
		selectedProject = null;
	}

	public void onProjectSelect(SelectEvent event) throws IOException {
		Project project = (Project) event.getObject();
		log.t("ProjectListController.onProjectSelect({0})", project);
		try {
			crud.startEdit(project);
		} catch (Exception e) {
			log.e("Erro ao tentar iniciar a edição do projeto: {0}", e, project);
		}
	}

	public void onProjectUnselect() {
		log.t("ProjectListController.onProjectUnselect()");
		this.setSelectedProject(null);
	}

	public void onNewProject() {
		log.t("ProjectListController.onNewProject()");
		this.setSelectedProject(null);
		try {
			crud.startNew();
		} catch (Exception e) {
			log.e("Erro ao tentar iniciar um novo projeto", e);
		}
	}

	public void removeProject() {
		log.t("ProjectListController.removeProject()");
		crud.remove();
		this.loadProjects();
	}

	public void saveProject() {
		log.t("ProjectListController.saveProject()");
		crud.save();
		this.loadProjects();
	}

	public Project getSelectedProject() {
		log.t("ProjectListController.getSelectedProject() : {0}",
				selectedProject);
		return selectedProject;
	}

	public void setSelectedProject(Project selectedProject) {
		log.t("ProjectListController.setSelectedProject({0})", selectedProject);
		this.selectedProject = selectedProject;
	}

	public List<Project> getProjects() {
		log.t("ProjectListController.getProjects() : {0}", projects);
		return projects;
	}

	public void setProjects(List<Project> projects) {
		log.t("ProjectListController.setProjects({0})", projects);
		this.projects = projects;
	}

	public ProjectCrudController getCrud() {
		return crud;
	}

	public void setCrud(ProjectCrudController crud) {
		this.crud = crud;
	}

	public StreamedContent getDownloadXmlFile() throws InvalidXmlEntryException {
		Project project = projectFacade.merge(crud.getProject());
		XmlParser<DbModel> parser = new XmlParser<>(DbModel.class);
		InputStream stream = new ByteArrayInputStream(parser.toXML(
				(DbModel) project.getModel()).getBytes());
		return new DefaultStreamedContent(stream, "text/xml", project
				.getName() + ".xml");
	}

	public void upload(FileUploadEvent event) {
		try {
			if (event.getFile() == null)
				throw new Exception("file is null");

			StringBuilder builder = new StringBuilder();
			BufferedReader reader = new BufferedReader(new InputStreamReader(
					event.getFile().getInputstream()));

			String lineRead = "";
			while ((lineRead = reader.readLine()) != null) {
				builder.append(lineRead);
			}
			XmlParser<DbModel> parser = new XmlParser<>(DbModel.class);
			try {
				DbModel model = parser.fromXML(builder.toString());
				model.setDatabase(databasesFacade.getDataBaseByName(model
						.getDatabase().getDb()));
				crud.getProject().setModel(model);
				FacesMessage msg = new FacesMessage("IMPORTAÇÃO", event
						.getFile().getFileName()
						+ " foi importado com sucesso!");
				FacesContext.getCurrentInstance().addMessage(null, msg);
			} catch (NoResultException e) {
				log.d("NoResultException: {0}", e.getMessage());
				FacesMessage msg = new FacesMessage(
						"Erro ao obter banco de dados do arquivo ", event
								.getFile().getFileName()
								+ ". Banco não encontrado!");
				FacesContext.getCurrentInstance().addMessage(null, msg);
			} catch (Exception e) {
				log.e("Erro ao importar arquivo1: {0}", e);
				FacesMessage msg = new FacesMessage(
						"Erro ao importar arquivo ", event.getFile()
								.getFileName() + ". Arquivo inválido!");
				FacesContext.getCurrentInstance().addMessage(null, msg);
			}

		} catch (Exception e) {
			log.e("Erro ao importar arquivo2: {0}", e);
			FacesMessage msg = new FacesMessage("ERRO",
					"Erro ao importar arquivo " + event.getFile().getFileName()
							+ ". " + e);
			FacesContext.getCurrentInstance().addMessage(null, msg);
			e.printStackTrace();
		}
	}

	public StreamedContent getDownloadSqlFile() throws TransformerException,
			InvalidXmlEntryException {
		ModelTranslator modelTranslator = new ModelTranslator();
		XmlParser<DbModel> parser = new XmlParser<>(DbModel.class);
		Project project = projectFacade.merge(crud.getProject());
		String xml = parser.toXML(project.getModel());
		String xsl = project.getModel().getDatabase().getXmlToSqlXsl();
		InputStream stream = new ByteArrayInputStream(modelTranslator.transform(xml, xsl).getBytes());
		return new DefaultStreamedContent(stream, "text/xml", project
				.getName() + ".sql");
	}

}

src/main/webapp/pages/user/index.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/resources/templates/defaultTemplate.xhtml" xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets" xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core">
	<ui:define name="pageName">
	Index
	</ui:define>

	<ui:define name="content">
	</ui:define>
</ui:composition>

src/main/webapp/pages/user/projetos.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/resources/templates/defaultTemplate.xhtml" xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
>
	<ui:define name="pageName">
	Projetos
	</ui:define>

	<ui:define name="content">

		<h:form id="frmCrudProject">
			<p:layout id="layoutProjectCrud" style="height:700px;text-align:center;">
				<p:blockUI block=":frmCrudProject:tableProjects" trigger=":frmCrudProject:tableProjects :frmCrudProject:save :frmCrudProject:remove">
					Carregando
					<br />
					<p:graphicImage library="images" name="loading.gif" />
				</p:blockUI>
				<p:layoutUnit position="center" header="Lista de Projetos">
					<p:dataTable id="tableProjects" value="#{projectListController.projects}" var="project" selection="#{projectListController.selectedProject}" selectionMode="single"
						rowKey="#{project.id}" emptyMessage="Você não possui nenhum projeto" styleClass="ui-shadow"
					>
						<p:ajax event="rowSelect" listener="#{projectListController.onProjectSelect}" update=":frmCrudProject:panelDetails" process="@this" />

						<p:column headerText="Código" sortBy="#{project.id}" filterBy="#{project.id}" filterMatchMode="startsWith">
							<h:outputText value="#{project.id}" />
						</p:column>
						<p:column headerText="Nome" sortBy="#{project.name}" filterBy="#{project.name}" filterMatchMode="contains">
							<h:outputText value="#{project.name}" />
						</p:column>
						<p:column headerText="Banco" sortBy="#{project.model.database.db}" filterBy="#{project.model.database.db}" filterMatchMode="contains">
							<h:outputText value="#{project.model.database.db}" />
						</p:column>
						<p:column headerText="Data de Criação" sortBy="#{project.creationDate}" filterBy="#{project.creationDate}" filterMatchMode="contains">
							<h:outputText value="#{project.creationDate}">
								<f:convertDateTime type="date" />
							</h:outputText>
						</p:column>
					</p:dataTable>
				</p:layoutUnit>
				<p:layoutUnit position="east" size="450" header="Detalhes do projeto" collapsible="true" resizable="true">
					<p:blockUI block=":frmCrudProject:panelDetails" trigger=":frmCrudProject:tableProjects :frmCrudProject:save :frmCrudProject:remove">
						Carregando
						<br />
						<p:graphicImage library="images" name="loading.gif" />
					</p:blockUI>
					<p:panel id="panelDetails" styleClass="ui-shadow">
						<f:facet name="header">

							<p:commandButton id="new" value="Novo" style="width:30%;" action="#{projectListController.onNewProject()}" disabled="#{projectListController.crud.new}" update="@form" />
							<p:commandButton id="save" value="Salvar" style="width:30%;" action="#{projectListController.saveProject()}" actionListener="#{projectListController.loadProjects()}"
								disabled="#{not projectListController.crud.active}" update="@form"
							/>
							<p:commandButton id="remove" value="Remover" style="width:30%;" action="#{projectListController.removeProject()}" actionListener="#{projectListController.loadProjects()}"
								disabled="#{not projectListController.crud.edit or not projectListController.crud.permission.isOwner()}" update="@form"
							/>

						</f:facet>
						<h:panelGroup rendered="#{projectListController.crud.active}">
							<h:panelGrid style="text-align:left;width:95%;" columns="1">
								<h:panelGroup id="nameProjectPanel">
									<h:outputLabel value="Nome: " for="inputNameProject" style="font-weight:bold" />
									<p:inputText id="inputNameProject" value="#{projectListController.crud.project.name}" required="true" readonly="#{not projectListController.crud.permission.canEdit()}"
										style="width:95%;"
									/>
								</h:panelGroup>
								<h:panelGroup id="databasePanel">
									<h:outputText value="Banco: " style="font-weight:bold"/>
									<p:selectOneMenu id="inputDataBaseProject" value="#{projectListController.crud.database}" style="width:99%;" converter="omnifaces.SelectItemsConverter"
										disabled="#{not projectListController.crud.permission.canEdit()}" required="true" rendered="#{projectListController.crud.database == null}"
									>
										<f:selectItem noSelectionOption="true" itemLabel="Selecione" />
										<f:selectItems value="#{projectListController.crud.datatypes}" var="datatype" itemLabel="#{datatype.db}" itemValue="#{datatype}" />
									</p:selectOneMenu>
									<h:outputText value="#{projectListController.crud.database.db}" rendered="#{projectListController.crud.database != null}" />
								</h:panelGroup>
							</h:panelGrid>
							<p:separator />
							<p:dataTable id="usersTable" var="alloweduser" value="#{projectListController.crud.project.allowedUsers}" rows="5" paginator="true" paginatorPosition="top"
								style="text-align:center;" styleClass="ui-shadow" emptyMessage="Nenhum usuario selecionado" rendered="#{projectListController.crud.permission.isOwner()}"
							>
								<f:facet name="header">
									<h:outputText value="Compatilhar projeto" />
								</f:facet>
								<p:column headerText="Login" id="loginColumn">
									<h:outputText value="#{alloweduser.user.login}  " />
								</p:column>
								<p:column headerText="Nome " id="nameColumn">
									<h:outputText value="#{alloweduser.user.name}" />
								</p:column>
								<p:column headerText="Permissão" id="readOnlyColumn" style="width:5%;">
									<p:selectBooleanButton id="readOnlyComboBox" value="#{alloweduser.readOnly}" onLabel="Leitura " offLabel="Edição" onIcon="ui-icon-locked" offIcon="ui-icon-unlocked" disabled="#{not projectListController.crud.permission.isOwner()}"/>
								</p:column>
								<p:column headerText="Ações" id="actionColumn" style="width:5%;">
									<p:commandButton id="removeUserButton" process="@parent" update="@form" icon="ui-icon-trash" value="Remover" action="#{projectListController.crud.removeUser()}"
										disabled="#{not projectListController.crud.permission.isOwner()}"
									>
										<f:setPropertyActionListener target="#{projectListController.crud.userSelected}" value="#{alloweduser.user}" />
									</p:commandButton>
								</p:column>
								<f:facet name="footer">
									<p:commandButton type="button" value="Inserir usuário" onclick="insertUserDialog.show();" icon="ui-icon-check"
										disabled="#{!projectListController.crud.permission.isOwner()}" process="@none" style="width:95%;"
									/>
								</f:facet>

							</p:dataTable>
							<p:panel rendered="#{!projectListController.crud.permission.isOwner()}">
								<h:outputLabel value="Projeto criado por:  " style="font-weight:bold" />
								<h:outputText value="#{projectListController.selectedProject.owner.name}"/>
							</p:panel>
							<br />

							<p:fieldset style="width:90%" toggleable="true" collapsed="true" legend="Importação/Exportação">
								<p:commandButton id="btnDownloadModel" value="Baixar Modelo XML" title="Exportar Modelo" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop)"
									icon="ui-icon-circle-arrow-s" rendered="#{projectListController.crud.active}" style="text-align:center;width:99%"
								>
									<p:fileDownload value="#{projectListController.downloadXmlFile}" />
								</p:commandButton>
								<p:commandButton id="btnDownloadSql" value="Baixar Script SQL" title="Baixar SQL" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop)"
									icon="ui-icon-circle-arrow-s" rendered="#{projectListController.crud.active}" style="text-align:center;width:99%"
								>
									<p:fileDownload value="#{projectListController.downloadSqlFile}" />
								</p:commandButton>
								<p:fileUpload style="text-align:center;border-width:0" fileUploadListener="#{projectListController.upload}" mode="advanced" auto="true" label="Submeter Modelo"
									sizeLimit="100000" update="databasePanel" allowTypes="/(\.|\/)(xml|xls)$/" rendered="#{projectListController.crud.active}" disabled="#{not projectListController.crud.permission.canEdit()}"
								/>
							</p:fieldset>
						</h:panelGroup>
						<f:facet name="footer">

							<p:button href="/pages/user/designer.xhtml?id=#{projectListController.crud.project.id}" ajax="false" id="btnOpenProject" value="Designer" icon="ui-icon-arrowreturnthick-1-n"
								title="Abrir Designer" style="width:99%;text-align:center;" rendered="#{projectListController.crud.active }" disabled="#{projectListController.selectedProject == null}"
							/>
						</f:facet>
					</p:panel>
				</p:layoutUnit>
			</p:layout>

			<p:dialog header="Inserir Usuário" widgetVar="insertUserDialog" resizable="false" modal="true" dynamic="true">
				<p:dataTable value="#{projectListController.crud.users}" var="insertUser" rowKey="#{insertUser.id}" rows="20" id="selectUserTable"
					selection="#{projectListController.crud.userSelected}" selectionMode="single"
				>
					<f:facet name="header">
						<h:outputLabel value="Selecione um usuário:" />
					</f:facet>
					<p:ajax event="rowSelect" listener="#{projectListController.crud.onUserSelect}" update=":frmCrudProject:usersTable @parent" oncomplete="insertUserDialog.hide()"
						process="@this"
					/>
					<p:column headerText="Login" id="login" filterMatchMode="contains" filterBy="#{insertUser.login}" sortBy="#{insertUser.login}">
						#{insertUser.login}
					</p:column>
					<p:column headerText="Nome " id="name" filterMatchMode="contains" filterBy="#{insertUser.name}" sortBy="#{insertUser.name}">
						#{insertUser.name}
					</p:column>
				</p:dataTable>
			</p:dialog>
		</h:form>
	</ui:define>
</ui:composition>