src/main/java/com/clouddesigner/controller/CurrentUserController.java
package com.clouddesigner.controller;

import java.io.Serializable;
import java.security.Principal;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.clouddesigner.entities.Role;
import com.clouddesigner.entities.User;
import com.clouddesigner.model.facade.UsersFacade;

@Named
@SessionScoped
public class CurrentUserController implements Serializable {

	private static final long serialVersionUID = 1L;

	private User usuario;

	@Inject
	private Principal userPrincipal;

	@Inject
	private UsersFacade usersFacade;

	@PostConstruct
	public void load() throws Exception {
		usuario = usersFacade.getByLogin(userPrincipal.getName());
	}

	public void logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	}

	public User getUsuario() {
		return usuario;
	}

	public boolean isLogado() {
		return this.getUsuario() != null;
	}

	public boolean isInRole(String role) {
		return FacesContext.getCurrentInstance().getExternalContext().isUserInRole(role);
	}

	public boolean isAdmin() {
		return isInRole("ADMIN");
	}

	public String getTheme() {
		if (usuario.getTheme() == null || usuario.getTheme().isEmpty())
			usuario.setTheme("black-tie");
		return usuario.getTheme();
	}

	public void setTheme(String theme) {
		usuario.setTheme(theme);
	}

	public void publishChange() {	
		usuario = usersFacade.update(usuario);
	}
	
	public String rolesUser(){
		StringBuffer roles = new StringBuffer();
		for(Role r: usuario.getRoles()){
			roles.append(r.getRoleName());
			roles.append(", ");
			
		}
		if(roles.length()>2)
			roles.replace(roles.length()-2, roles.length()-1, "");
		return roles.toString();
	}
	
	public String getLogin(){
		return usuario.getLogin();
	}
	
}

src/main/webapp/resources/templates/defaultTemplate.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
>


<h:head>
	<title>
		Database Cloud Designer -
		<ui:insert name="pageName" />
	</title>
	<h:outputStylesheet library="css" name="template.css" />
	<h:outputScript library="javascript" name="jquery.ui.touch-punch.min.js" />

</h:head>
<h:body>
	<h:form id="menuForm" prependId="false"> 
		<div id="header" class="ui-widget ui-widget-header">
			<p:graphicImage id="logo" library="images" name="logo.png" />
			<div id="pageInfo">
				<h:outputText value="Bem vindo " /><p:commandLink value="#{currentUserController.usuario.name}" onclick="dlgProfile.show();" />
				<br />
				<h:outputText value="Você está em: " />
				<ui:insert name="pageName" />
			</div>
			<div id="themeRoller">
				<h:outputLabel for="cbTema" value="Tema: " />
				<p:themeSwitcher value="#{currentUserController.theme}" style="width:165px" effect="fade" id="cbTema">
					<f:selectItem itemLabel="Choose Theme" itemValue="" />
					<f:selectItems value="#{themeSwitcherBean.themes}" />
					<p:ajax listener="#{currentUserController.publishChange()}" process="@this" />
				</p:themeSwitcher>
			</div>
		</div>

		<ui:insert name="menuBar">
			<p:menubar id="menuGeral" rendered="#{currentUserController.logado}">
				<p:menuitem id="menuInicio" value="Home" url="/" ajax="false" />
				<p:menuitem id="menuProjectList" value="Projetos" url="/pages/user/projetos.xhtml" ajax="false" />
				<p:menuitem id="menuDatabaseManager" value="Bases de dados" url="/pages/admin/databasesManager.xhtml" ajax="false" rendered="#{currentUserController.admin}" />
				<p:menuitem id="menuUserManager" value="Usuarios" url="/pages/admin/usersManager.xhtml" ajax="false" rendered="#{currentUserController.admin}" />
			</p:menubar>
		</ui:insert>
	</h:form>
	<p:growl autoUpdate="true" showDetail="true" />
	<div id="content">
		<ui:insert name="content">
		</ui:insert>
	</div>
	<p:dialog id="profileDialog" header="Perfil" widgetVar="dlgProfile" modal="true" height="300" width="500">  
    	<h:form>
	    	<p:panel>
	    		
	    		<h:panelGrid columns="2" style="width:100%;">
		    		<h:outputLabel value="Login:" style="font-weight:bold"  />
		    		<h:outputText id="inputLogin" value="#{currentUserController.login}" />
		    		<h:outputLabel value="Nome:" style="font-weight:bold"  />
		    		<p:inputText id="inputName" value="#{currentUserController.usuario.name}" />
		    		<h:outputLabel value="Senha:"  style="font-weight:bold" />
		    		<p:password id="inputPassword" redisplay="true" value="#{currentUserController.usuario.password}" />
		    		<h:outputLabel value="Permissões: " style="font-weight:bold"  />
		    		<h:outputText value="#{currentUserController.rolesUser()}" />
	    		</h:panelGrid>
	    		<f:facet name="footer">
	    			<div id="footerDlgProfile" style="width:100%;text-align:center;">
						<p:commandButton id="btnUpdateProfile" value="Salvar"
							action="#{currentUserController.publishChange()}"
							update=":menuForm" oncomplete="dlgProfile.hide();" 
							process="@form"/>
					</div>
	    		</f:facet>
	    	</p:panel>
	    </h:form>
	</p:dialog>
</h:body>
</html>