src/main/java/com/clouddesigner/controller/CurrentUserController.java
package com.clouddesigner.controller;

import java.io.Serializable;
import java.security.Principal;

import javax.annotation.PostConstruct;
import javax.enterprise.context.SessionScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.inject.Named;

import com.clouddesigner.entities.Role;
import com.clouddesigner.entities.User;
import com.clouddesigner.model.facade.UsersFacade;

@Named
@SessionScoped
public class CurrentUserController implements Serializable {

	private static final long serialVersionUID = 1L;

	private User usuario;

	@Inject
	private Principal userPrincipal;

	@Inject
	private UsersFacade usersFacade;

	@PostConstruct
	public void load() throws Exception {
		usuario = usersFacade.getByLogin(userPrincipal.getName());
	}

	public void logout() {
		FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
	}

	public User getUsuario() {
		return usuario;
	}

	public boolean isLogado() {
		return this.getUsuario() != null;
	}

	public boolean isInRole(String role) {
		return FacesContext.getCurrentInstance().getExternalContext().isUserInRole(role);
	}

	public boolean isAdmin() {
		return isInRole("ADMIN");
	}

	public String getTheme() {
		if (usuario.getTheme() == null || usuario.getTheme().isEmpty())
			usuario.setTheme("black-tie");
		return usuario.getTheme();
	}

	public void setTheme(String theme) {
		usuario.setTheme(theme);
	}

	public void publishChange() {	
		usuario = usersFacade.update(usuario);
	}
	
	public String rolesUser(){
		StringBuffer roles = new StringBuffer();
		for(Role r: usuario.getRoles()){
			roles.append(r.getRoleName());
			roles.append(", ");
			
		}
		if(roles.length()>2)
			roles.replace(roles.length()-2, roles.length()-1, "");
		return roles.toString();
	}
	
	public String getLogin(){
		return usuario.getLogin();
	}
	
}

src/main/java/com/clouddesigner/controller/ProjectCrudController.java
package com.clouddesigner.controller;

import java.io.Serializable;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.annotation.PreDestroy;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.inject.Inject;
import javax.transaction.NotSupportedException;
import javax.transaction.SystemException;

import org.primefaces.event.SelectEvent;

import com.clouddesigner.component.model.datatype.DataTypeModel;
import com.clouddesigner.controller.util.ControllerState;
import com.clouddesigner.entities.AllowedUser;
import com.clouddesigner.entities.Project;
import com.clouddesigner.entities.User;
import com.clouddesigner.entities.transients.Permission;
import com.clouddesigner.model.facade.DatabasesFacade;
import com.clouddesigner.model.facade.ProjectFacade;
import com.clouddesigner.model.facade.ProjectInstancesManagerFacade;
import com.clouddesigner.model.facade.UsersFacade;
import com.clouddesigner.util.log.Log;

public class ProjectCrudController implements Serializable {
	private static final long serialVersionUID = 1L;
	@Inject
	private Log log;
	@Inject
	private UsersFacade usersFacade;
	@Inject
	private DatabasesFacade databasesFacade;
	@Inject
	private ProjectFacade projectFacade;
	@Inject
	private ProjectInstancesManagerFacade projectEditorFacade;
	@Inject
	private CurrentUserController userController;
	private List<DataTypeModel> datatypes;
	private List<User> users;
	private Project project;
	private User userSelected;
	private Permission permission;
	private ControllerState state = ControllerState.NONE;

	@PostConstruct
	public void init() throws NotSupportedException, SystemException {
		log.t("ProjectCrudController.init() : " + state);
		datatypes = databasesFacade.getAllDatabases();
		users = usersFacade.getAllUsers();
	}

	public void startEdit(Project project) throws SystemException,
			NotSupportedException {
		if (isActive())
			this.finish();
		this.project = projectFacade.merge(project);
		users = usersFacade.getAllUsers();

		users.remove(userController.getUsuario());
		for (AllowedUser a : this.project.getAllowedUsers())
			users.remove(a.getUser());

		log.t("ProjectCrudController.startEdit({0})", project);
		this.permission = projectEditorFacade.openProject(this.project,
				userController.getUsuario());
		this.state = ControllerState.EDITING;
	}

	public void startNew() throws SystemException, NotSupportedException {
		if (isActive())
			this.finish();
		users = usersFacade.getAllUsers();
		users.remove(userController.getUsuario());
		log.t("ProjectCrudController.startNew()");
		this.project = new Project(userController.getUsuario());
		this.permission = new Permission(userController.getUsuario().getId(),
				Permission.OWNER);
		this.state = ControllerState.ADDING;
	}

	public String save() {
		log.t("ProjectCrudController.save({0})", project);
		try {
			project = projectFacade.insert(project);
			state = ControllerState.NONE;
			return "/pages/user/designer.xhtml?faces-redirect=true&id="
					+ project.getId();
		} catch (Exception e) {
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR,
							"Erro ao salvar o projeto",
							"Foi interceptado o seguinte erro ao tentar salvar o projeto:\n"
									+ e.getClass().getName() + "["
									+ e.getMessage()
									+ "]\nPara mais detalhes veja o log"));
			log.e("Erro ao salvar o projeto {0}", e, project);
			return null;
		}

	}

	public void remove() {
		log.t("ProjectCrudController.remove({0})", project);
		if (isEdit()) {
			try {
				projectFacade.remove(project);
				state = ControllerState.NONE;
			} catch (Exception e) {
				FacesContext.getCurrentInstance().addMessage(
						null,
						new FacesMessage(FacesMessage.SEVERITY_ERROR,
								"Erro ao deletar o projeto",
								"Foi interceptado o seguinte erro ao tentar deletar o projeto:\n"
										+ e.getClass().getName() + "["
										+ e.getMessage()
										+ "]\nPara mais detalhes veja o log"));
				log.e("Erro ao salvar o projeto {0}", e, project);
			}
		}
	}

	public void setDatabase(DataTypeModel database) {
		log.t("ProjectCrudController.setDatabase({0})", database);
		project.getModel().setDatabase(database);
	}

	public DataTypeModel getDatabase() {
		log.t("ProjectCrudController.getDatabase() : {0}", project.getModel()
				.getDatabase());
		return project.getModel().getDatabase();
	}

	@PreDestroy
	public void finish() throws IllegalStateException, SecurityException,
			SystemException {
		log.t("ProjectCrudController.finish()");
	}

	public void removeUser() {
		log.t("ProjectCrudController.removeUser({0})", userSelected);
		for (AllowedUser usersPermission : project.getAllowedUsers()) {
			log.t("analisando {0}", usersPermission);
			if (usersPermission.getUser().getId().equals(userSelected.getId())) {
				log.t("removendo {0}", usersPermission);
				project.getAllowedUsers().remove(usersPermission);
				projectFacade.removeAllowedUser(usersPermission);
				break;
			}
		}

		users.add(userSelected);
		userSelected = null;
	}

	public void onUserSelect(SelectEvent event) {
		User user = ((User) event.getObject());
		log.t("ProjectCrudController.onUserSelect({0})", user);
		project.getAllowedUsers().add(new AllowedUser(false, project, user));
		users.remove(userSelected);
		userSelected = null;
	}

	public Project getProject() {
		log.t("ProjectCrudController.getProject() : {0}", project);
		return project;
	}

	public void setProject(Project project) {
		log.t("ProjectCrudController.setProject({0})", project);
		this.project = project;
	}

	public List<AllowedUser> getAllowedUser() {
		log.t("ProjectCrudController.getAllowedUser() : {0}",
				project.getAllowedUsers());
		return project.getAllowedUsers();
	}

	public void setAllowedUser(List<AllowedUser> allowedUsers) {
		log.t("ProjectCrudController.setAllowedUser({0})", allowedUsers);
		project.setAllowedUsers(allowedUsers);
	}

	public List<User> getUsers() {
		log.t("ProjectCrudController.getUsers() : {0}", users);
		return users;
	}

	public void setUsers(List<User> users) {
		log.t("ProjectCrudController.setUsers({0})", users);
		this.users = users;
	}

	public List<DataTypeModel> getDatatypes() {
		log.t("ProjectCrudController.getDatatypes() : {0}", datatypes);
		return datatypes;
	}

	public void setDatatypes(List<DataTypeModel> datatypes) {
		log.t("ProjectCrudController.setDatatypes({0})", datatypes);
		this.datatypes = datatypes;
	}

	public User getUserSelected() {
		log.t("ProjectCrudController.getUserSelected() : {0}", userSelected);
		return userSelected;
	}

	public void setUserSelected(User userSelected) {
		log.t("ProjectCrudController.setUserSelected({0})", userSelected);
		this.userSelected = userSelected;
	}

	public Permission getPermission() {
		log.t("ProjectCrudController.getPermission() : {0}", permission);
		return permission;
	}

	public void setPermission(Permission permission) {
		log.t("ProjectCrudController.setPermission({0})", permission);
		this.permission = permission;
	}

	public ControllerState getState() {
		return state;
	}

	public void setState(ControllerState state) {
		this.state = state;
	}

	public boolean isActive() {
		boolean active = !state.equals(ControllerState.NONE);
		log.t("ProjectCrudController.isActive() : {0}", active);
		return active;
	}

	public boolean isNew() {
		boolean adding = state.equals(ControllerState.ADDING);
		log.t("ProjectCrudController.isNew() : {0}", adding);
		return adding;
	}

	public boolean isEdit() {
		boolean editing = state.equals(ControllerState.EDITING);
		log.t("ProjectCrudController.isEdit() : {0}", editing);
		return editing;
	}

}

src/main/webapp/pages/admin/databasesManager.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/resources/templates/defaultTemplate.xhtml" xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
>

	<ui:define name="content">
		<h:form id="dbForm" style="text-align:center;" enctype="multipart/form-data">
			<p:layout style="height:500px;width:100%;padding-top:10px;">
				<p:layoutUnit position="center">
					<p:dataTable id="loadedDbsTable" widgetVar="jsLoadedDbsTable" var="model" value="#{databasesCrudController.loadedDataTypes}" rows="10" paginator="true" selectionMode="single"
						selection="#{databasesCrudController.selectedDataType}" rowKey="#{model.id}"
					>
						<p:ajax event="rowSelect" listener="#{databasesCrudController.onRowSelect}" update=":dbForm:pnlCrudDatabase" />

						<f:facet name="header">
							<h:outputText value="Bancos de Dados Cadastrados" />
						</f:facet>

						<p:column headerText="Código" style="width:10%;" sortBy="#{model.id}" filterBy="#{model.id}">
							<h:outputText value="#{model.id}" />
						</p:column>

						<p:column headerText="Nome" sortBy="#{model.db}" filterBy="#{model.db}">
							<h:outputText value="#{model.db}" />
						</p:column>

					</p:dataTable>
				</p:layoutUnit>
				<p:layoutUnit id="eastUnit" position="east" size="30%" resizable="true" collapsible="true" header="Detalhes">

					<p:panel id="pnlCrudDatabase" style="width:98%;">
						<f:facet name="header">
							<p:commandButton value="Novo" style="width:30%;" action="#{databasesCrudController.startNew()}" update="@form" disabled="#{databasesCrudController.new}" />
							<p:commandButton value="Salvar" style="width:30%;" action="#{databasesCrudController.save()}" update="@form" disabled="#{not databasesCrudController.active}" />
							<p:commandButton value="Deletar" style="width:30%;" action="#{databasesCrudController.remove()}" update="@form" disabled="#{not databasesCrudController.edit}" />
						</f:facet>
						<p:fileUpload fileUploadListener="#{databasesCrudController.handleFileUpload}" mode="advanced" multiple="true" label="Arquivos" update="dBViewer" sizeLimit="100000"
							allowTypes="/(\.|\/)(xml|xsl)$/" style="width:98%;" rendered="#{databasesCrudController.active}"
						/>

						<h:panelGroup id="dBViewer" style="width:100%;text-align:left;">
							<h:panelGroup rendered="#{databasesCrudController.active}">
								<h:outputText value="Este modelo ainda não possui XSL para conversão em SQL" rendered="#{empty databasesCrudController.xmlToSqlXsl}" />
								<h:outputText value="Possui XSL para conversão em SQL" rendered="#{not empty databasesCrudController.xmlToSqlXsl}" />
							</h:panelGroup>
							<br />
							<p:tree id="treeNodeDb" widgetVar="jsTreeNodeDb" value="#{databasesCrudController.root}" var="node" rendered="#{not empty databasesCrudController.root}" style="width:100%;">
								<p:treeNode>
									<h:outputText id="lblNode" value="#{node}" />
								</p:treeNode>
							</p:tree>
						</h:panelGroup>
						<f:facet name="footer">
							<p:commandButton value="XSL" style="width:49%;text-align:center;" rendered="#{not empty databasesCrudController.xmlToSqlXsl}" icon="ui-icon-circle-arrow-s" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop)">
								<p:fileDownload value="#{databasesCrudController.downloadXsl()}" />
							</p:commandButton>
							<p:commandButton value="Datatype" style="width:49%;text-align:center;" rendered="#{not empty databasesCrudController.xmlToSqlXsl}" icon="ui-icon-circle-arrow-s" ajax="false" onclick="PrimeFaces.monitorDownload(start, stop)">
								<p:fileDownload value="#{databasesCrudController.downloadXmlDatatype()}" />
							</p:commandButton>
						</f:facet>
					</p:panel>
				</p:layoutUnit>
			</p:layout>
		</h:form>
	</ui:define>
</ui:composition>

src/main/webapp/pages/admin/usersManager.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition template="/resources/templates/defaultTemplate.xhtml" xmlns="http://www.w3.org/1999/xhtml" xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui" xmlns:h="http://java.sun.com/jsf/html" xmlns:f="http://java.sun.com/jsf/core"
>

	<ui:define name="content">
		<h:form id="usersForm" prependId="false" style="text-align:center;"	>
			<p:layout id="usersLayout" widgetVar="jsUsersLayout" style="width:100%;height:500px;padding-top:10px;">
				<p:layoutUnit id="usersCenterLayout" position="center">

					<p:dataTable id="usersDataTable" widgetVar="jsUsersDataTable" var="user" value="#{usersCrudController.availableUsers}" rows="10" 
						paginator="true" selectionMode="single"	selection="#{usersCrudController.selectedUser}" rowKey="#{user.id}"
					>
						<f:facet name="header">
							<h:outputText value="Usuários Cadastrados" />
						</f:facet>

						<p:ajax event="rowSelect" listener="#{usersCrudController.onRowSelect}" update="@form" />

						<p:column headerText="Id" style="width:25%">
							<h:outputText value="#{user.id}" />
						</p:column>

						<p:column headerText="Login" style="width:25%">
							<h:outputText value="#{user.login}" />
						</p:column>

						<p:column headerText="Nome" style="width:25%">
							<h:outputText value="#{user.name}" />
						</p:column>

						<p:column headerText="Permissões" style="width:25%">
							<h:outputText value="#{usersCrudController.rolesUser(user)}" />
							
						</p:column>
					</p:dataTable>

				</p:layoutUnit>
				<p:layoutUnit id="usersEastLayout" position="east" size="30%" collapsible="true" header="Detalhes">
					<p:panel style="text-align:center;">

						<f:facet name="header">
							<p:commandButton value="Novo" disabled="#{usersCrudController.opController.newDisabled}" action="#{usersCrudController.actionNewUser()}" update="@form" style="width:30%;" />
							<p:commandButton value="Salvar" disabled="#{usersCrudController.opController.saveDisabled}" action="#{usersCrudController.actionSaveUser()}" update="@form"
								style="width:30%;"
							/>
							<p:commandButton value="Deletar" disabled="#{usersCrudController.opController.deleteDisabled}" action="#{usersCrudController.actionDeleteUser()}" update="@form"
								style="width:30%;"
							/>
						</f:facet>

						<p:separator />

						<p:panelGrid columns="2" style="width:100%;text-align:center;">
							<h:outputLabel value="Login:" for="userLoginId" />
							<p:inputText id="userLoginId" value="#{usersCrudController.selectedUser.login}" style="width:95%;" disabled="#{usersCrudController.opController.saveDisabled}" />

							<h:outputLabel value="Nome:" for="userNameId" />
							<p:inputText id="userNameId" value="#{usersCrudController.selectedUser.name}" style="width:95%;" disabled="#{usersCrudController.opController.saveDisabled}" />

							<h:outputLabel value="Senha:" for="userPasswordId" />
							<p:password id="userPasswordId" redisplay="true" value="#{usersCrudController.selectedUser.password}" style="width:95%;" disabled="#{usersCrudController.opController.saveDisabled}" />

							<h:outputLabel value="Permissão:" />
							<p:selectCheckboxMenu  value="#{usersCrudController.selectedRoles}" style="width:98%;" label="Permissões disponíveis" filter="true" filterText="Filter"
								filterMatchMode="startsWith" disabled="#{usersCrudController.opController.saveDisabled}"
							>
								<f:selectItems value="#{usersCrudController.availableRoles}" />
							</p:selectCheckboxMenu>
						</p:panelGrid>

					</p:panel>
				</p:layoutUnit>
			</p:layout>
		</h:form>
		
	</ui:define>
</ui:composition>